# Generated by Django 5.1.4 on 2025-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='picture/', width_field='width'),
        ),
    ]
