# Generated by Django 5.1.4 on 2025-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_picture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='enable_comments',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
